// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Container extends pulumi.CustomResource {
    /**
     * Get an existing Container resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ContainerState, opts?: pulumi.CustomResourceOptions): Container {
        return new Container(name, <any>state, { ...opts, id: id });
    }

    public readonly attach: pulumi.Output<boolean | undefined>;
    public /*out*/ readonly bridge: pulumi.Output<string>;
    public readonly capabilities: pulumi.Output<{ adds?: string[], drops?: string[] } | undefined>;
    public readonly command: pulumi.Output<string[] | undefined>;
    public /*out*/ readonly containerLogs: pulumi.Output<string>;
    public readonly cpuSet: pulumi.Output<string | undefined>;
    public readonly cpuShares: pulumi.Output<number | undefined>;
    public readonly destroyGraceSeconds: pulumi.Output<number | undefined>;
    public readonly devices: pulumi.Output<{ containerPath?: string, hostPath: string, permissions?: string }[] | undefined>;
    public readonly dns: pulumi.Output<string[] | undefined>;
    public readonly dnsOpts: pulumi.Output<string[] | undefined>;
    public readonly dnsSearches: pulumi.Output<string[] | undefined>;
    public readonly domainname: pulumi.Output<string | undefined>;
    public readonly entrypoints: pulumi.Output<string[] | undefined>;
    public readonly envs: pulumi.Output<string[] | undefined>;
    public /*out*/ readonly exitCode: pulumi.Output<number>;
    public /*out*/ readonly gateway: pulumi.Output<string>;
    /**
     * A test to perform to check that the container is healthy
     */
    public readonly healthcheck: pulumi.Output<{ interval?: string, retries?: number, startPeriod?: string, tests: string[], timeout?: string } | undefined>;
    public readonly hosts: pulumi.Output<{ host: string, ip: string }[] | undefined>;
    public readonly hostname: pulumi.Output<string | undefined>;
    public readonly image: pulumi.Output<string>;
    public /*out*/ readonly ipAddress: pulumi.Output<string>;
    public /*out*/ readonly ipPrefixLength: pulumi.Output<number>;
    public readonly labels: pulumi.Output<{[key: string]: any} | undefined>;
    public readonly links: pulumi.Output<string[] | undefined>;
    public readonly logDriver: pulumi.Output<string | undefined>;
    public readonly logOpts: pulumi.Output<{[key: string]: any} | undefined>;
    public readonly logs: pulumi.Output<boolean | undefined>;
    public readonly maxRetryCount: pulumi.Output<number | undefined>;
    public readonly memory: pulumi.Output<number | undefined>;
    public readonly memorySwap: pulumi.Output<number | undefined>;
    public readonly mustRun: pulumi.Output<boolean | undefined>;
    public readonly name: pulumi.Output<string>;
    /**
     * Set an alias for the container in all specified networks
     */
    public readonly networkAliases: pulumi.Output<string[] | undefined>;
    public /*out*/ readonly networkDatas: pulumi.Output<{ gateway: string, ipAddress: string, ipPrefixLength: number, networkName: string }[]>;
    public readonly networkMode: pulumi.Output<string | undefined>;
    public readonly networks: pulumi.Output<string[] | undefined>;
    public readonly networksAdvanced: pulumi.Output<{ aliases?: string[], ipv4Address?: string, ipv6Address?: string, name: string }[] | undefined>;
    public readonly pidMode: pulumi.Output<string | undefined>;
    public readonly ports: pulumi.Output<{ external: number, internal: number, ip?: string, protocol?: string }[] | undefined>;
    public readonly privileged: pulumi.Output<boolean | undefined>;
    public readonly publishAllPorts: pulumi.Output<boolean | undefined>;
    public readonly restart: pulumi.Output<string | undefined>;
    public readonly rm: pulumi.Output<boolean | undefined>;
    public readonly start: pulumi.Output<boolean | undefined>;
    public readonly ulimits: pulumi.Output<{ hard: number, name: string, soft: number }[] | undefined>;
    public readonly uploads: pulumi.Output<{ content: string, executable?: boolean, file: string }[] | undefined>;
    public readonly user: pulumi.Output<string | undefined>;
    public readonly usernsMode: pulumi.Output<string | undefined>;
    public readonly volumes: pulumi.Output<{ containerPath?: string, fromContainer?: string, hostPath?: string, readOnly?: boolean, volumeName?: string }[] | undefined>;

    /**
     * Create a Container resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ContainerArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ContainerArgs | ContainerState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state: ContainerState = argsOrState as ContainerState | undefined;
            inputs["attach"] = state ? state.attach : undefined;
            inputs["bridge"] = state ? state.bridge : undefined;
            inputs["capabilities"] = state ? state.capabilities : undefined;
            inputs["command"] = state ? state.command : undefined;
            inputs["containerLogs"] = state ? state.containerLogs : undefined;
            inputs["cpuSet"] = state ? state.cpuSet : undefined;
            inputs["cpuShares"] = state ? state.cpuShares : undefined;
            inputs["destroyGraceSeconds"] = state ? state.destroyGraceSeconds : undefined;
            inputs["devices"] = state ? state.devices : undefined;
            inputs["dns"] = state ? state.dns : undefined;
            inputs["dnsOpts"] = state ? state.dnsOpts : undefined;
            inputs["dnsSearches"] = state ? state.dnsSearches : undefined;
            inputs["domainname"] = state ? state.domainname : undefined;
            inputs["entrypoints"] = state ? state.entrypoints : undefined;
            inputs["envs"] = state ? state.envs : undefined;
            inputs["exitCode"] = state ? state.exitCode : undefined;
            inputs["gateway"] = state ? state.gateway : undefined;
            inputs["healthcheck"] = state ? state.healthcheck : undefined;
            inputs["hosts"] = state ? state.hosts : undefined;
            inputs["hostname"] = state ? state.hostname : undefined;
            inputs["image"] = state ? state.image : undefined;
            inputs["ipAddress"] = state ? state.ipAddress : undefined;
            inputs["ipPrefixLength"] = state ? state.ipPrefixLength : undefined;
            inputs["labels"] = state ? state.labels : undefined;
            inputs["links"] = state ? state.links : undefined;
            inputs["logDriver"] = state ? state.logDriver : undefined;
            inputs["logOpts"] = state ? state.logOpts : undefined;
            inputs["logs"] = state ? state.logs : undefined;
            inputs["maxRetryCount"] = state ? state.maxRetryCount : undefined;
            inputs["memory"] = state ? state.memory : undefined;
            inputs["memorySwap"] = state ? state.memorySwap : undefined;
            inputs["mustRun"] = state ? state.mustRun : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["networkAliases"] = state ? state.networkAliases : undefined;
            inputs["networkDatas"] = state ? state.networkDatas : undefined;
            inputs["networkMode"] = state ? state.networkMode : undefined;
            inputs["networks"] = state ? state.networks : undefined;
            inputs["networksAdvanced"] = state ? state.networksAdvanced : undefined;
            inputs["pidMode"] = state ? state.pidMode : undefined;
            inputs["ports"] = state ? state.ports : undefined;
            inputs["privileged"] = state ? state.privileged : undefined;
            inputs["publishAllPorts"] = state ? state.publishAllPorts : undefined;
            inputs["restart"] = state ? state.restart : undefined;
            inputs["rm"] = state ? state.rm : undefined;
            inputs["start"] = state ? state.start : undefined;
            inputs["ulimits"] = state ? state.ulimits : undefined;
            inputs["uploads"] = state ? state.uploads : undefined;
            inputs["user"] = state ? state.user : undefined;
            inputs["usernsMode"] = state ? state.usernsMode : undefined;
            inputs["volumes"] = state ? state.volumes : undefined;
        } else {
            const args = argsOrState as ContainerArgs | undefined;
            if (!args || args.image === undefined) {
                throw new Error("Missing required property 'image'");
            }
            inputs["attach"] = args ? args.attach : undefined;
            inputs["capabilities"] = args ? args.capabilities : undefined;
            inputs["command"] = args ? args.command : undefined;
            inputs["cpuSet"] = args ? args.cpuSet : undefined;
            inputs["cpuShares"] = args ? args.cpuShares : undefined;
            inputs["destroyGraceSeconds"] = args ? args.destroyGraceSeconds : undefined;
            inputs["devices"] = args ? args.devices : undefined;
            inputs["dns"] = args ? args.dns : undefined;
            inputs["dnsOpts"] = args ? args.dnsOpts : undefined;
            inputs["dnsSearches"] = args ? args.dnsSearches : undefined;
            inputs["domainname"] = args ? args.domainname : undefined;
            inputs["entrypoints"] = args ? args.entrypoints : undefined;
            inputs["envs"] = args ? args.envs : undefined;
            inputs["healthcheck"] = args ? args.healthcheck : undefined;
            inputs["hosts"] = args ? args.hosts : undefined;
            inputs["hostname"] = args ? args.hostname : undefined;
            inputs["image"] = args ? args.image : undefined;
            inputs["labels"] = args ? args.labels : undefined;
            inputs["links"] = args ? args.links : undefined;
            inputs["logDriver"] = args ? args.logDriver : undefined;
            inputs["logOpts"] = args ? args.logOpts : undefined;
            inputs["logs"] = args ? args.logs : undefined;
            inputs["maxRetryCount"] = args ? args.maxRetryCount : undefined;
            inputs["memory"] = args ? args.memory : undefined;
            inputs["memorySwap"] = args ? args.memorySwap : undefined;
            inputs["mustRun"] = args ? args.mustRun : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["networkAliases"] = args ? args.networkAliases : undefined;
            inputs["networkMode"] = args ? args.networkMode : undefined;
            inputs["networks"] = args ? args.networks : undefined;
            inputs["networksAdvanced"] = args ? args.networksAdvanced : undefined;
            inputs["pidMode"] = args ? args.pidMode : undefined;
            inputs["ports"] = args ? args.ports : undefined;
            inputs["privileged"] = args ? args.privileged : undefined;
            inputs["publishAllPorts"] = args ? args.publishAllPorts : undefined;
            inputs["restart"] = args ? args.restart : undefined;
            inputs["rm"] = args ? args.rm : undefined;
            inputs["start"] = args ? args.start : undefined;
            inputs["ulimits"] = args ? args.ulimits : undefined;
            inputs["uploads"] = args ? args.uploads : undefined;
            inputs["user"] = args ? args.user : undefined;
            inputs["usernsMode"] = args ? args.usernsMode : undefined;
            inputs["volumes"] = args ? args.volumes : undefined;
            inputs["bridge"] = undefined /*out*/;
            inputs["containerLogs"] = undefined /*out*/;
            inputs["exitCode"] = undefined /*out*/;
            inputs["gateway"] = undefined /*out*/;
            inputs["ipAddress"] = undefined /*out*/;
            inputs["ipPrefixLength"] = undefined /*out*/;
            inputs["networkDatas"] = undefined /*out*/;
        }
        super("docker:index/container:Container", name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Container resources.
 */
export interface ContainerState {
    readonly attach?: pulumi.Input<boolean>;
    readonly bridge?: pulumi.Input<string>;
    readonly capabilities?: pulumi.Input<{ adds?: pulumi.Input<pulumi.Input<string>[]>, drops?: pulumi.Input<pulumi.Input<string>[]> }>;
    readonly command?: pulumi.Input<pulumi.Input<string>[]>;
    readonly containerLogs?: pulumi.Input<string>;
    readonly cpuSet?: pulumi.Input<string>;
    readonly cpuShares?: pulumi.Input<number>;
    readonly destroyGraceSeconds?: pulumi.Input<number>;
    readonly devices?: pulumi.Input<pulumi.Input<{ containerPath?: pulumi.Input<string>, hostPath: pulumi.Input<string>, permissions?: pulumi.Input<string> }>[]>;
    readonly dns?: pulumi.Input<pulumi.Input<string>[]>;
    readonly dnsOpts?: pulumi.Input<pulumi.Input<string>[]>;
    readonly dnsSearches?: pulumi.Input<pulumi.Input<string>[]>;
    readonly domainname?: pulumi.Input<string>;
    readonly entrypoints?: pulumi.Input<pulumi.Input<string>[]>;
    readonly envs?: pulumi.Input<pulumi.Input<string>[]>;
    readonly exitCode?: pulumi.Input<number>;
    readonly gateway?: pulumi.Input<string>;
    /**
     * A test to perform to check that the container is healthy
     */
    readonly healthcheck?: pulumi.Input<{ interval?: pulumi.Input<string>, retries?: pulumi.Input<number>, startPeriod?: pulumi.Input<string>, tests: pulumi.Input<pulumi.Input<string>[]>, timeout?: pulumi.Input<string> }>;
    readonly hosts?: pulumi.Input<pulumi.Input<{ host: pulumi.Input<string>, ip: pulumi.Input<string> }>[]>;
    readonly hostname?: pulumi.Input<string>;
    readonly image?: pulumi.Input<string>;
    readonly ipAddress?: pulumi.Input<string>;
    readonly ipPrefixLength?: pulumi.Input<number>;
    readonly labels?: pulumi.Input<{[key: string]: any}>;
    readonly links?: pulumi.Input<pulumi.Input<string>[]>;
    readonly logDriver?: pulumi.Input<string>;
    readonly logOpts?: pulumi.Input<{[key: string]: any}>;
    readonly logs?: pulumi.Input<boolean>;
    readonly maxRetryCount?: pulumi.Input<number>;
    readonly memory?: pulumi.Input<number>;
    readonly memorySwap?: pulumi.Input<number>;
    readonly mustRun?: pulumi.Input<boolean>;
    readonly name?: pulumi.Input<string>;
    /**
     * Set an alias for the container in all specified networks
     */
    readonly networkAliases?: pulumi.Input<pulumi.Input<string>[]>;
    readonly networkDatas?: pulumi.Input<pulumi.Input<{ gateway?: pulumi.Input<string>, ipAddress?: pulumi.Input<string>, ipPrefixLength?: pulumi.Input<number>, networkName?: pulumi.Input<string> }>[]>;
    readonly networkMode?: pulumi.Input<string>;
    readonly networks?: pulumi.Input<pulumi.Input<string>[]>;
    readonly networksAdvanced?: pulumi.Input<pulumi.Input<{ aliases?: pulumi.Input<pulumi.Input<string>[]>, ipv4Address?: pulumi.Input<string>, ipv6Address?: pulumi.Input<string>, name: pulumi.Input<string> }>[]>;
    readonly pidMode?: pulumi.Input<string>;
    readonly ports?: pulumi.Input<pulumi.Input<{ external?: pulumi.Input<number>, internal: pulumi.Input<number>, ip?: pulumi.Input<string>, protocol?: pulumi.Input<string> }>[]>;
    readonly privileged?: pulumi.Input<boolean>;
    readonly publishAllPorts?: pulumi.Input<boolean>;
    readonly restart?: pulumi.Input<string>;
    readonly rm?: pulumi.Input<boolean>;
    readonly start?: pulumi.Input<boolean>;
    readonly ulimits?: pulumi.Input<pulumi.Input<{ hard: pulumi.Input<number>, name: pulumi.Input<string>, soft: pulumi.Input<number> }>[]>;
    readonly uploads?: pulumi.Input<pulumi.Input<{ content: pulumi.Input<string>, executable?: pulumi.Input<boolean>, file: pulumi.Input<string> }>[]>;
    readonly user?: pulumi.Input<string>;
    readonly usernsMode?: pulumi.Input<string>;
    readonly volumes?: pulumi.Input<pulumi.Input<{ containerPath?: pulumi.Input<string>, fromContainer?: pulumi.Input<string>, hostPath?: pulumi.Input<string>, readOnly?: pulumi.Input<boolean>, volumeName?: pulumi.Input<string> }>[]>;
}

/**
 * The set of arguments for constructing a Container resource.
 */
export interface ContainerArgs {
    readonly attach?: pulumi.Input<boolean>;
    readonly capabilities?: pulumi.Input<{ adds?: pulumi.Input<pulumi.Input<string>[]>, drops?: pulumi.Input<pulumi.Input<string>[]> }>;
    readonly command?: pulumi.Input<pulumi.Input<string>[]>;
    readonly cpuSet?: pulumi.Input<string>;
    readonly cpuShares?: pulumi.Input<number>;
    readonly destroyGraceSeconds?: pulumi.Input<number>;
    readonly devices?: pulumi.Input<pulumi.Input<{ containerPath?: pulumi.Input<string>, hostPath: pulumi.Input<string>, permissions?: pulumi.Input<string> }>[]>;
    readonly dns?: pulumi.Input<pulumi.Input<string>[]>;
    readonly dnsOpts?: pulumi.Input<pulumi.Input<string>[]>;
    readonly dnsSearches?: pulumi.Input<pulumi.Input<string>[]>;
    readonly domainname?: pulumi.Input<string>;
    readonly entrypoints?: pulumi.Input<pulumi.Input<string>[]>;
    readonly envs?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A test to perform to check that the container is healthy
     */
    readonly healthcheck?: pulumi.Input<{ interval?: pulumi.Input<string>, retries?: pulumi.Input<number>, startPeriod?: pulumi.Input<string>, tests: pulumi.Input<pulumi.Input<string>[]>, timeout?: pulumi.Input<string> }>;
    readonly hosts?: pulumi.Input<pulumi.Input<{ host: pulumi.Input<string>, ip: pulumi.Input<string> }>[]>;
    readonly hostname?: pulumi.Input<string>;
    readonly image: pulumi.Input<string>;
    readonly labels?: pulumi.Input<{[key: string]: any}>;
    readonly links?: pulumi.Input<pulumi.Input<string>[]>;
    readonly logDriver?: pulumi.Input<string>;
    readonly logOpts?: pulumi.Input<{[key: string]: any}>;
    readonly logs?: pulumi.Input<boolean>;
    readonly maxRetryCount?: pulumi.Input<number>;
    readonly memory?: pulumi.Input<number>;
    readonly memorySwap?: pulumi.Input<number>;
    readonly mustRun?: pulumi.Input<boolean>;
    readonly name?: pulumi.Input<string>;
    /**
     * Set an alias for the container in all specified networks
     */
    readonly networkAliases?: pulumi.Input<pulumi.Input<string>[]>;
    readonly networkMode?: pulumi.Input<string>;
    readonly networks?: pulumi.Input<pulumi.Input<string>[]>;
    readonly networksAdvanced?: pulumi.Input<pulumi.Input<{ aliases?: pulumi.Input<pulumi.Input<string>[]>, ipv4Address?: pulumi.Input<string>, ipv6Address?: pulumi.Input<string>, name: pulumi.Input<string> }>[]>;
    readonly pidMode?: pulumi.Input<string>;
    readonly ports?: pulumi.Input<pulumi.Input<{ external?: pulumi.Input<number>, internal: pulumi.Input<number>, ip?: pulumi.Input<string>, protocol?: pulumi.Input<string> }>[]>;
    readonly privileged?: pulumi.Input<boolean>;
    readonly publishAllPorts?: pulumi.Input<boolean>;
    readonly restart?: pulumi.Input<string>;
    readonly rm?: pulumi.Input<boolean>;
    readonly start?: pulumi.Input<boolean>;
    readonly ulimits?: pulumi.Input<pulumi.Input<{ hard: pulumi.Input<number>, name: pulumi.Input<string>, soft: pulumi.Input<number> }>[]>;
    readonly uploads?: pulumi.Input<pulumi.Input<{ content: pulumi.Input<string>, executable?: pulumi.Input<boolean>, file: pulumi.Input<string> }>[]>;
    readonly user?: pulumi.Input<string>;
    readonly usernsMode?: pulumi.Input<string>;
    readonly volumes?: pulumi.Input<pulumi.Input<{ containerPath?: pulumi.Input<string>, fromContainer?: pulumi.Input<string>, hostPath?: pulumi.Input<string>, readOnly?: pulumi.Input<boolean>, volumeName?: pulumi.Input<string> }>[]>;
}
