// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class RemoteImage extends pulumi.CustomResource {
    /**
     * Get an existing RemoteImage resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RemoteImageState, opts?: pulumi.CustomResourceOptions): RemoteImage {
        return new RemoteImage(name, <any>state, { ...opts, id: id });
    }

    public readonly keepLocally: pulumi.Output<boolean | undefined>;
    public /*out*/ readonly latest: pulumi.Output<string>;
    public readonly name: pulumi.Output<string>;
    public readonly pullTrigger: pulumi.Output<string | undefined>;
    public readonly pullTriggers: pulumi.Output<string[] | undefined>;

    /**
     * Create a RemoteImage resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RemoteImageArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RemoteImageArgs | RemoteImageState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state: RemoteImageState = argsOrState as RemoteImageState | undefined;
            inputs["keepLocally"] = state ? state.keepLocally : undefined;
            inputs["latest"] = state ? state.latest : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["pullTrigger"] = state ? state.pullTrigger : undefined;
            inputs["pullTriggers"] = state ? state.pullTriggers : undefined;
        } else {
            const args = argsOrState as RemoteImageArgs | undefined;
            if (!args || args.name === undefined) {
                throw new Error("Missing required property 'name'");
            }
            inputs["keepLocally"] = args ? args.keepLocally : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["pullTrigger"] = args ? args.pullTrigger : undefined;
            inputs["pullTriggers"] = args ? args.pullTriggers : undefined;
            inputs["latest"] = undefined /*out*/;
        }
        super("docker:index/remoteImage:RemoteImage", name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering RemoteImage resources.
 */
export interface RemoteImageState {
    readonly keepLocally?: pulumi.Input<boolean>;
    readonly latest?: pulumi.Input<string>;
    readonly name?: pulumi.Input<string>;
    readonly pullTrigger?: pulumi.Input<string>;
    readonly pullTriggers?: pulumi.Input<pulumi.Input<string>[]>;
}

/**
 * The set of arguments for constructing a RemoteImage resource.
 */
export interface RemoteImageArgs {
    readonly keepLocally?: pulumi.Input<boolean>;
    readonly name: pulumi.Input<string>;
    readonly pullTrigger?: pulumi.Input<string>;
    readonly pullTriggers?: pulumi.Input<pulumi.Input<string>[]>;
}
